## ----setup, include=FALSE-------------------------------------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)


## ----libs, message=FALSE, warning=FALSE,class.source = 'fold-show'--------------------------------------
list.of.packages <-
  c(
    "dplyr",
    "tidyr",
    "ggplot2",
    "conflicted", #Some functions are named the same way across different packages and they can be conflicts and this package helps sorting this problem 
    "here", #helps with the reproducibility across operating systems=
    "plotly", #  another advanced visualization tool 
    "emdbook" #Library needed to obtain samples from a beta-binomial distribution
  )

new.packages <-
  list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]

#Download packages that are not already present in the library
if (length(new.packages))
  install.packages(new.packages)

# Load packages
packages_load <-
  lapply(list.of.packages, require, character.only = TRUE)

#Print warning if there is a problem with installing/loading some of packages
if (any(as.numeric(packages_load) == 0)) {
  warning(paste("Package/s: ", paste(list.of.packages[packages_load != TRUE], sep = ", "), "not loaded!"))
} else {
  print("All packages were successfully loaded.")
}
rm(list.of.packages, new.packages, packages_load)

#Resolve conflicts/ if all 
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("layout", "plotly")

#if install is not working try changing repositories
#install.packages("ROCR", repos = c(CRAN="https://cran.r-project.org/"))


## ----cv_calc,class.source = 'fold-show'-----------------------------------------------------------------
n_plants <- 50 #  The total number of plants
infected <- 20 # Number of infected plants
(incidence  <- infected /n_plants) #  Disease incidence 
(var <- (incidence* (1 - incidence))/n_plants) # Variance
(cv <- sqrt(var)/incidence) # Coefficient of variation
cv * 100 # Often expressed in percentages


## ----half_width_calc,class.source = 'fold-show'---------------------------------------------------------
(1.96*sqrt(var))/incidence # H: Half-width of the required confidence interval
1.96*sqrt(var) # 


## ----N_M_N0_calc----------------------------------------------------------------------------------------
gg <- 
expand.grid(
  N0 = seq(5,50, by = 5), 
  M = seq(100, 4000,50 )
) %>% 
  as_tibble() %>% 
  mutate(N = round(N0/(1+(N0/M)),2)
         ) %>% 
  arrange(N0) %>% 
  ggplot(aes(M, N, group = N0,color=  N0))+
  geom_point()+
  geom_line(aes(M, N, group = N0,color=  N0))+
  geom_point(size = .4)+
  scale_color_viridis_c()+
  scale_y_continuous(name="N", limits=c(0, 50), breaks = seq(5,50, by = 5))+
  theme_bw()+
  theme(panel.grid.major.y = element_line(color = "gray",
                                          size = 0.5,
                                          linetype = 2))
gg


## ----plotlyplot_N_M_N0, fig.width=9, fig.height=7.5,class.source = 'fold-show'--------------------------
plotly::ggplotly(gg) %>% 
  plotly::layout(legend = list(orientation = "h", x = 0.4, y = -0.2))


## ----func,class.source = 'fold-show'--------------------------------------------------------------------
EstNfcf <- function (M, mean, CV) {
  return((1 - mean) / (mean * CV ^ 2))
}
EstFcf <- function (M, mean, CV) {
  Nest <- (1 - mean) / (mean * CV ^ 2)
  finite <- Nest / M
  Nsample <- ifelse(finite > 0.1,
                    Nest / (1 + (Nest / M)), 
                    Nest)
  return(round(Nsample, digits = 1))
}
NestM <- function (M, mean, CV) {
  Nest <- (1 - mean) / (mean * CV ^ 2)
  finite <- Nest / M
  return(round(finite, digits = 2))
}



## ----data_prep, fig.width=9, fig.height=7.5,class.source = 'fold-show'----------------------------------
gg <-
as.data.frame(expand.grid(
  mean =seq(.1, .9, .1),
  CV =seq(.05, .3, .01), 
  M =  c(100, 500, 1000)
  ) ) %>% 
  mutate( 
         est_nfcf = EstNfcf(M,mean,CV),
         est_fcf = EstFcf(M,mean,CV),
         nest_m = NestM(M,mean,CV)
  ) %>% 
  #Multiplication factor(in brackets) to make the differences obvious on the plot
  mutate("NEST/M(X100)" = nest_m *100,
         "Estimated-FCF(X5)" = est_fcf*5,
         "Estimated-NFCF" = est_nfcf) %>% 
  pivot_longer(cols = c("Estimated-NFCF", "Estimated-FCF(X5)", "NEST/M(X100)"),
               values_to = "sample_size") %>% 
ggplot(aes(CV, sample_size, group = mean, color = mean))+
  geom_point(size = .5)+
  geom_line()+
  scale_color_viridis_c()+
  facet_grid(M~name)+
  theme_bw()+
  theme(legend.position = "top")




## ----plotlyplot, fig.width=9, fig.height=7.5,class.source = 'fold-show'---------------------------------
plotly::ggplotly(gg) %>% 
  plotly::layout(legend = list(orientation = "h", x = 0.4, y = -0.2))


## -------------------------------------------------------------------------------------------------------
set.seed(101)
field1<-rbinom(n=300, size=10, prob=0.25)


## -------------------------------------------------------------------------------------------------------
field1.matrix<-matrix(field1,nrow=15,ncol=20)
field1.matrix
map1_long <- 
  reshape2::melt(field1.matrix, varnames = c("rows", "cols")) 
# See first rows onf melted matrix
head(map1_long)
point_size <- 11
map1_long %>% 
  ggplot(aes(factor(cols), factor(rows), 
             color = value,
             label = as.character(value)))+
  geom_point(size = point_size, shape = 15)+
  geom_text(colour = "black")+
  scale_color_gradient("Health status (counts of infected plants):",
                       low = "lightgreen", high = "#993300")+
  theme_bw()+
  theme(axis.title = element_blank(),
        legend.position = "top",
        panel.background = element_rect(terrain.colors(5)[3]),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  coord_equal()


## -------------------------------------------------------------------------------------------------------
set.seed(500)
field1.sample<-sample(x=field1, size=25)
field1.sample


## -------------------------------------------------------------------------------------------------------
(field1.sampleB<-field1.sample/10)
(field1.mean<-mean(field1.sampleB))
(field1.var<-var(field1.sampleB) )#Variance based on normal distribution
(field1.varbin<-(field1.mean*(1-field1.mean))/10)


## -------------------------------------------------------------------------------------------------------
field1.var/field1.varbin


## -------------------------------------------------------------------------------------------------------
N1<-(1-field1.mean)/(10*field1.mean*0.1^2)
N1

N2<-(1-field1.mean)/(10*field1.mean*0.2^2)
N2


## -------------------------------------------------------------------------------------------------------
set.seed(10000)
field2<-rbetabinom(n=300, prob=0.35, size=10, shape1=0.2, shape2=2)

field2.matrix<-matrix(field2,nrow=15,ncol=20)
field2.matrix

map1_long <- 
  reshape2::melt(field2.matrix, varnames = c("rows", "cols")) 
# See first rows onf melted matrix
head(map1_long)
point_size <- 11
map1_long %>% 
  ggplot(aes(factor(cols), factor(rows), 
             color = value,
             label = as.character(value)))+
  geom_point(size = point_size, shape = 15)+
  geom_text(colour = "black")+
  scale_color_gradient("Health status (counts of infected plants):",
                       low = "lightgreen", high = "#993300")+
  theme_bw()+
  theme(axis.title = element_blank(),
        legend.position = "top",
        panel.background = element_rect(terrain.colors(5)[3]),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  coord_equal()


## -------------------------------------------------------------------------------------------------------
set.seed(602)
field2.sample<-sample(x=field2, size=25)
field2.sample


## -------------------------------------------------------------------------------------------------------
field2.sampleB<-field2.sample/10
field2.mean<-mean(field2.sampleB)
field2.var<-var(field2.sampleB) #Variance based on normal distribution
field2.varbin<-(field2.mean*(1-field2.mean))/10


## -------------------------------------------------------------------------------------------------------
var.relation<-field2.var/field2.varbin


## -------------------------------------------------------------------------------------------------------
N1<-(1-field1.mean)/(10*field1.mean*0.1^2)
N1

N2<-(1-field1.mean)/(10*field1.mean*0.2^2)
N2


## -------------------------------------------------------------------------------------------------------
N1<-(1-field1.mean)/(10*field1.mean*0.1^2)
N1

N2<-(1-field1.mean)/(10*field1.mean*0.2^2)
N2


## -------------------------------------------------------------------------------------------------------
A<-16
B<-1.4
CV1 <- .1
CV2 <- .2


## -------------------------------------------------------------------------------------------------------
(N.power1<-(A*field2.mean^(B-2)*(1-field2.mean)^B)/(10^B*CV1^2))
(N.power2<-(A*field2.mean^(B-2)*(1-field2.mean)^B)/(10^B*CV2^2))


## -------------------------------------------------------------------------------------------------------
deff = 2.54
CV1 <- .1
CV2 <- .2

N.betabinom1 <- ((1 - field2.mean) * deff) / (10 * field2.mean * CV1 ^ 2)
N.betabinom2 <- ((1 - field2.mean) * deff) / (10 * field2.mean * CV2 ^ 2)


## ----func2----------------------------------------------------------------------------------------------
SRS.PROPORTION.1 <- function (mean,z,H) {
  Nest<-((1-mean)/mean)*(z/H)^2
  names(Nest)<-"SampleSize"
  return(Nest)
}



## ----plotlyplot2, fig.width=6, fig.height=5-------------------------------------------------------------
gg <-
  as.data.frame(expand.grid(
    mean = seq(.05, .3, .05),
    z = 1.96,
    H =  seq(.1, .5, .05)
  )) %>%
  mutate(SampleSize = SRS.PROPORTION.1(mean, z, H)) %>%
  ggplot(aes(H, SampleSize, group = mean, color = mean)) +
  geom_point(size = .5) +
  geom_line() +
  scale_color_viridis_c() +
  theme_bw()

plotly::ggplotly(gg) 


## ----func3----------------------------------------------------------------------------------------------
EstNfcf <- function (M,mean,z,H) {
  return(((1-mean)/mean)*(z/H)^2)
}
EstFcf <- function (M,mean,z,H) {
  Nest<-((1-mean)/mean)*(z/H)^2
  finite <-Nest/M
  Nsample <-ifelse(finite>0.1,Nest/(1+(Nest/M)),Nest)
  return(round(Nsample,digits=1))
}
NestM <- function (M,mean,z,H) {
  Nest <-((1-mean)/mean)*(z/H)^2
  finite <-Nest/M
  return(round(finite, digits=2))
}



## ----data_prep3, fig.width=9, fig.height=7.5------------------------------------------------------------
gg <- 
  as.data.frame(expand.grid(
    mean = seq(.05, .3, .05),
    z = 1.96, 
    H =  seq(.1,.5,.05),
    M =1000
  ) ) %>% 
  mutate( 
    est_nfcf = EstNfcf(M,mean,z,H),
    est_fcf = EstFcf(M,mean,z,H),
    nest_m = NestM(M,mean,z,H)
  ) %>% 
  mutate("NEST/M" = nest_m ,
         "Estimated-FCF" = est_fcf,
         "Estimated-NFCF" = est_nfcf) %>% 
  pivot_longer(cols = c("Estimated-NFCF", "Estimated-FCF", "NEST/M")) %>% 
  ggplot(aes(H, value, group = mean, color = mean))+
  geom_point(size = .5)+
  geom_line()+
  scale_color_viridis_c()+
  facet_wrap(~name, ncol = 1, scales = "free_y")+
  theme_bw()+
  theme(legend.position = "top")


## ----plotlyplot3, fig.width=9, fig.height=7.5-----------------------------------------------------------
plotly::ggplotly(gg) %>% 
  plotly::layout(legend = list(orientation = "h", x = 0.4, y = -0.2))


## ----func4----------------------------------------------------------------------------------------------
SRS.PROPORTION.1 <- function (mean,z,h) {
  Nest<-(mean*(1-mean))*(z/h)^2
  names(Nest)<-"SampleSize"
  return(Nest)
}


## ----plotlyplot4, fig.width=6, fig.height=5-------------------------------------------------------------
gg <- 
as.data.frame(expand.grid(
  mean = seq(.05, .3, .05),
  z = 1.96, 
  h =  seq(.1,.5,.05)
) ) %>% 
  mutate( 
    SampleSize = SRS.PROPORTION.1(mean,z,h)
  ) %>% 
  ggplot(aes(h, SampleSize, group = mean, color = mean))+
  geom_point(size = .5)+
  geom_line()+
  scale_color_viridis_c()+
  theme_bw()

plotly::ggplotly(gg) 


## ----func5----------------------------------------------------------------------------------------------
EstNfcf <- function (mean, n, CV, M) {
  return(round((1 - mean) / (n * mean * CV ^ 2), 2))
}
EstFcf <- function (mean, n, CV, M) {
  Nest <- (1 - mean) / (n * mean * CV ^ 2)
  finite <- Nest / M
  Nsample <- ifelse(finite > 0.1, Nest / (1 + (Nest / M)), Nest)
  return(round(Nsample, digits = 1))
}
NestM <- function (mean, n, CV, M) {
  Nest <- (1 - mean) / (n * mean * CV ^ 2)
  finite <- Nest / M
  return(round(finite, digits = 2))
}



## ----data_prep5, fig.width=9, fig.height=7.5------------------------------------------------------------
gg <-
as.data.frame(expand.grid(
  mean =seq(.1, .9, .1),
  n = 10,
  CV =seq(.05, .3, .01), 
  M =  c(100, 500, 1000)
)) %>%
  mutate(
    est_nfcf = EstNfcf(mean, n, CV, M),
    est_fcf = EstFcf(mean, n, CV, M),
    nest_m = NestM(mean, n, CV, M)
  ) %>%
  mutate("NEST/M(X100)" = nest_m *100,
         "Estimated-FCF" = est_fcf,
         "Estimated-NFCF" = est_nfcf) %>% 
  pivot_longer(cols = c("Estimated-NFCF", "Estimated-FCF", "NEST/M(X100)")) %>% 
  ggplot(aes(CV, value, group = mean, color = mean))+
  geom_point(size = .5)+
  geom_line()+
  scale_color_viridis_c()+
  facet_grid(M~name)+
  theme_bw()+
  theme(legend.position = "top")


## ----plotlyplot5, fig.width=9, fig.height=7.5-----------------------------------------------------------
plotly::ggplotly(gg) %>% 
  plotly::layout(legend = list(orientation = "h", x = 0.4, y = -0.2))


## ----func6----------------------------------------------------------------------------------------------
CLUSTER.RANDOM.2 <- function (mean, n, z, H) {
  Nest<-((1-mean)/(n*mean))*(z/H)^2
  names(Nest)<-"SampleSize"
  return(Nest)
}



## ----plotlyplot6, fig.width=6, fig.height=5-------------------------------------------------------------
gg <-
  as.data.frame(expand.grid(
    mean = seq(.05, .3, .05),
    n = 10,
    z = 1.96,
    H =  seq(.1, .5, .05)
  )) %>%
  mutate(SampleSize = CLUSTER.RANDOM.2(mean, n, z, H)) %>%
  ggplot(aes(H, SampleSize, group = mean, color = mean)) +
  geom_point(size = .5) +
  geom_line() +
  scale_color_viridis_c() +
  theme_bw()

plotly::ggplotly(gg) 


## ----func7----------------------------------------------------------------------------------------------
CLUSTER.RANDOM.3 <- function(mean, n, z, h) {
  Nest <- ((mean * (1 - mean)) / n) * (z / h) ^ 2
  names(Nest) <- "SampleSize"
  return(Nest)
}



## ----plotlyplot7, fig.width=6, fig.height=5-------------------------------------------------------------
gg <- 
as.data.frame(expand.grid(
  mean = seq(.05, .3, .05),
  n = 10,
  z = 1.96, 
  h =  seq(.01,.1,.01)
) ) %>% 
  mutate( 
    SampleSize = CLUSTER.RANDOM.3(mean,n, z,h)
  ) %>% 
  ggplot(aes(h, SampleSize, group = mean, color = mean))+
  geom_point(size = .5)+
  geom_line()+
  scale_color_viridis_c()+
  theme_bw()

plotly::ggplotly(gg) 

